### ISSUE TITLE
Multi-line code snippets are concatenated into one line

### ISSUE THREAD

**Issue by BehindTheMath** [skx/markdownshare.com#6]
Multi-line code is not displayed correctly, but is concatenated into a single line.

For example:
````
```
{
    "key": "value"
}
```
````
is displayed as:

`{ "key": "value" }`

instead of:
```
{
    "key": "value"
}
```

**Comment by skx** [comment]
Thanks for the bug-report!

You didn't create a sample link for me to look at so I created this:

* [The input](https://markdownshare.com/raw/4e696c87-d01d-49a7-9a3c-3277370f05f4)
* [The output](https://markdownshare.com/view/4e696c87-d01d-49a7-9a3c-3277370f05f4)

As you can see the output is "broken" as per your bug report, but interestingly if you look at the source of the rendered page it looks perfect.  Which led me down a rabbit-hole of looking at CSS.  As per several stackoverflow searchs I found that this resolves the problem:

     code {
        white-space: pre-wrap;
      }

With that hacked in suddenly the space shows up as expected.  I'll submit a fix with that done properly soon - but it is live now, so if you have an existing document that is broken it should be fine now, though you might need to force-reload to update the sites' CSS.
