### ISSUE TITLE
Sporadic 502 error

### ISSUE THREAD

**Issue by ArtskydJ** [skx/markdownshare.com#7]
Sometimes when I load the site, I get a 502 error, and sometimes I don't...

When I do get the 502 error it looks like this:
![untitled](https://user-images.githubusercontent.com/1833684/33401277-5afb5a90-d51e-11e7-9ac3-7a3db0c575f3.png)

**Comment by skx** [comment]
That's a strange-one, thanks for the report.  I'll try to look into it shortly.
